name: planner_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+3

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  flutter_svg: ^2.0.4
  google_sign_in: ^6.0.2
  flutter_secure_storage: ^8.0.0
  otp_text_field: ^1.1.1
  cloud_firestore: ^4.4.5
  image_picker: ^0.8.7
  flutter_dotenv: ^5.0.2
  learning_translate: ^0.0.3+1
  permission_handler: ^11.0.1
  uuid: ^3.0.7
  wakelock: ^0.6.2
  encrypt: ^5.0.0
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.1
  shared_preferences: ^2.2.2
  local_auth: ^2.1.7
  percent_indicator: ^4.2.3
  barcode_scan2: ^4.3.0
  totp: ^0.0.1
  qr_flutter: ^4.1.0
  timer_builder: ^2.0.0
  clipboard: ^0.1.3
  crypto: ^3.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

 
  assets:
    - assets/
